Repository Shamrock-code/Shamrock, pull requests merged in 2025-05, with the labels that each got.

#949 [Git] change mdspan remote to http
  .gitmodules
  .pre-commit-config.yaml
  buildbot/check_no_ssh_in_submodules.py
Labels: In-review

#850 [Ramses][io] add shamrock native dump.
  exemples/godunov_sedov.py
  src/shammodels/ramses/include/shammodels/ramses/Model.hpp
  src/shammodels/ramses/include/shammodels/ramses/Solver.hpp
  src/shammodels/ramses/include/shammodels/ramses/SolverConfig.hpp
  src/shammodels/ramses/src/pyRamsesModel.cpp
  src/shammodels/sph/include/shammodels/sph/SolverConfig.hpp
  src/shamrock/include/shamrock/io/units_json.hpp
  src/shamrock/include/shamrock/patch/PatchDataLayout.hpp
  src/shamrock/src/patch/PatchDataLayout.cpp
Labels: Polishing

#951 [Ramses] fix a typo in face interpolation
  src/shammodels/ramses/src/modules/FaceInterpolate.cpp
Labels: In-review

#953 [Patch] fix a missing const on PatchDataFieldSpan accessors
  src/shamrock/include/shamrock/patch/PatchDataFieldSpan.hpp
Labels: In-review

#954 [Ci] add concurency group to have only a single CI running per PR
  .github/workflows/on_pr.yml
Labels: In-review

#955 [Base] add set diff & on_distributeddata_diff
  src/shambase/include/shambase/DistributedData.hpp
  src/shambase/include/shambase/sets.hpp
  src/tests/shambase/setsTests.cpp
Labels: In-review

#957 [CI] add github page artifact to PR report
  .github/workflows/make_documentation.yml
  .github/workflows/make_website.yml
Labels: Draft

#958 [Backends] allow const DistributedData use in distributed kernel call
  src/shambackends/include/shambackends/kernel_call_distrib.hpp
  src/shambase/include/shambase/DistributedData.hpp
  src/shamrock/include/shamrock/patch/PatchDataFieldSpan.hpp
  src/tests/shambackends/kernel_call_distribTests.cpp
Labels: In-review

#956 [Doc] update packaging information, quickstart guide and README
  CITATION.bib
  README.md
  doc/mkdocs/docs/usermanual/quickstart.md
  doc/mkdocs/docs/usermanual/quickstart/install_brew.md
  doc/mkdocs/docs/usermanual/quickstart/install_docker.md
  doc/mkdocs/docs/usermanual/quickstart/install_from_source.md
  doc/mkdocs/docs/usermanual/quickstart/install_spack.md
  doc/mkdocs/mkdocs.yml
Labels: In-review

#959 [SolverGraph] add shamrock solvergraph API to compose modules
  src/shamrock/include/shamrock/solvergraph/Field.hpp
  src/shamrock/include/shamrock/solvergraph/FieldSpan.hpp
  src/shamrock/include/shamrock/solvergraph/IDataEdge.hpp
  src/shamrock/include/shamrock/solvergraph/IDataEdgeNamed.hpp
  src/shamrock/include/shamrock/solvergraph/INode.hpp
  src/shamrock/include/shamrock/solvergraph/Indexes.hpp
  src/shamrock/include/shamrock/solvergraph/OperationSequence.hpp
  src/shamrock/src/solvergraph/OperationSequence.cpp
Labels: In-review

#965 [SolverGraph] wrap IDataEdge tex symbol in brackets
  src/shamrock/include/shamrock/solvergraph/IDataEdgeNamed.hpp
Labels: Polishing

#966 [Models] make set_solver_config consistent across models
  exemples/ci_tests/sod_tube_godunov.py
  exemples/ci_tests/sod_tube_zeus.py
  exemples/godunov_advect.py
  exemples/godunov_dust_advect.py
  exemples/godunov_dusty_collision_test.py
  exemples/godunov_dusty_wave_test.py
  exemples/godunov_sedov.py
  exemples/godunov_sod.py
  exemples/godunov_soundwave.py
  exemples/sod_tube_godunov_amr.py
  exemples/zeus_advect.py
  exemples/zeus_sod.py
  exemples/zeus_soundwave.py
  src/shammodels/ramses/include/shammodels/ramses/SolverConfig.hpp
  src/shammodels/ramses/src/pyRamsesModel.cpp
  src/shammodels/sph/include/shammodels/sph/Model.hpp
  src/shammodels/zeus/include/shammodels/zeus/SolverConfig.hpp
  src/shammodels/zeus/src/pyAMRZeusModel.cpp
  src/shamrock/include/shamrock/scheduler/ShamrockCtx.hpp
Labels: In-review

#968 [CI] report tests error using Github action log format
  src/shamcmdopt/CMakeLists.txt
  src/shamcmdopt/include/shamcmdopt/ci_env.hpp
  src/shamcmdopt/src/ci_env.cpp
  src/shamtest/shamtest.cpp
Labels: In-review

#969 [CI] clean test outputs with MPI
  src/shambindings/include/shambindings/start_python.hpp
  src/shambindings/src/start_python.cpp
  src/shamcomm/include/shamcomm/collectives.hpp
  src/shamcomm/include/shamcomm/worldInfo.hpp
  src/shamcomm/src/collectives.cpp
  src/shamtest/shamtest.cpp
  src/tests/shamcomm/collectivesTests.cpp
Labels: In-review

#970 [SolverGraph] new FieldRefs layer, between Field and FieldSpan
  src/shamrock/include/shamrock/solvergraph/Field.hpp
  src/shamrock/include/shamrock/solvergraph/FieldRefs.hpp
  src/shamrock/include/shamrock/solvergraph/FieldSpan.hpp
Labels: In-review

#973 [Shamcomm] fix: remove extra print in gather_str
  src/shamcomm/src/collectives.cpp
Labels: In-review

#975 [Solvergraph] make edge span & ref getter abstract using interfaces
  src/shammodels/ramses/include/shammodels/ramses/modules/ConsToPrimDust.hpp
  src/shammodels/ramses/include/shammodels/ramses/modules/ConsToPrimGas.hpp
  src/shammodels/ramses/src/modules/ConsToPrim.cpp
  src/shammodels/ramses/src/modules/ConsToPrimDust.cpp
  src/shammodels/ramses/src/modules/ConsToPrimGas.cpp
  src/shamrock/include/shamrock/solvergraph/Field.hpp
  src/shamrock/include/shamrock/solvergraph/FieldRefs.hpp
  src/shamrock/include/shamrock/solvergraph/FieldSpan.hpp
  src/shamrock/include/shamrock/solvergraph/IFieldRefs.hpp
  src/shamrock/include/shamrock/solvergraph/IFieldSpan.hpp
  src/shamrock/include/shamrock/solvergraph/IFreeableDataEdge.hpp
Labels: In-review

#911 [Env] add env for Argonne Aurora supercomputer
  cmake/ShamrockBuildOptions.cmake
  env/machine/argonne/aurora/1device_per_process.sh
  env/machine/argonne/aurora/1device_per_process_directgpu.sh
  env/machine/argonne/aurora/1tile_per_process.sh
  env/machine/argonne/aurora/1tile_per_process_directgpu.sh
  env/machine/argonne/aurora/env_oneapi.sh
  env/machine/argonne/aurora/setup-env.py
  env/utils/envscript.py
  src/shamsys/include/shamsys/EnvVariables.hpp
Labels: Draft

#976 [Solvergraph] Implement NodeFreeAlloc to add alloc freeing in the graph
  src/shammodels/ramses/include/shammodels/ramses/modules/ConsToPrimDust.hpp
  src/shammodels/ramses/include/shammodels/ramses/modules/ConsToPrimGas.hpp
  src/shamrock/include/shamrock/solvergraph/Field.hpp
  src/shamrock/include/shamrock/solvergraph/FieldRefs.hpp
  src/shamrock/include/shamrock/solvergraph/FieldSpan.hpp
  src/shamrock/include/shamrock/solvergraph/IDataEdge.hpp
  src/shamrock/include/shamrock/solvergraph/IFreeable.hpp
  src/shamrock/include/shamrock/solvergraph/INode.hpp
  src/shamrock/include/shamrock/solvergraph/Indexes.hpp
  src/shamrock/include/shamrock/solvergraph/NodeFreeAlloc.hpp
  src/shamrock/include/shamrock/solvergraph/OperationSequence.hpp
  src/shamrock/src/solvergraph/OperationSequence.cpp
Labels: Polishing

#961 [Ramses][solvergraph PR 2] move ConsToPrim spans & field to SolverStorage
  src/shammodels/ramses/include/shammodels/ramses/Solver.hpp
  src/shammodels/ramses/include/shammodels/ramses/modules/SolverStorage.hpp
  src/shammodels/ramses/src/Model.cpp
  src/shammodels/ramses/src/Solver.cpp
  src/shammodels/ramses/src/modules/ComputeGradient.cpp
  src/shammodels/ramses/src/modules/ConsToPrim.cpp
  src/shammodels/ramses/src/modules/FaceInterpolate.cpp
  src/shammodels/ramses/src/modules/GhostZones.cpp
Labels: Polishing

#977 [Ci] fix missreporting of test errors in github action
  src/shamtest/shamtest.cpp
Labels: Polishing

#978 [CI] add godunov tests with dust
  .github/workflows/shamrock-acpp-phys-test.yml
  exemples/ci_tests/dustybox_godunov.py
  exemples/ci_tests/dustywave_godunov.py
Labels: In-review

#962 [Ramses][solvergraph PR 3] replace ConsToPrim by solvergraph modules
  src/shammodels/ramses/CMakeLists.txt
  src/shammodels/ramses/include/shammodels/ramses/modules/ConsToPrim.hpp
  src/shammodels/ramses/include/shammodels/ramses/modules/SolverStorage.hpp
  src/shammodels/ramses/src/Solver.cpp
  src/shammodels/ramses/src/modules/ConsToPrim.cpp
Labels: In-review

#980 [Math] Improve LatticeHCP performance
  src/shambackends/include/shambackends/math.hpp
  src/shammath/include/shammath/crystalLattice.hpp
  src/shammodels/sph/include/shammodels/sph/modules/setup/GeneratorLatticeHCP.hpp
  src/shamtest/shamtest.hpp
  src/tests/shammath/DiscontinuousIteratorTests.cpp
  src/tests/shammath/crystalLatticeTests.cpp
Labels: In-review

#982 [Comm][Aurora pullback] improve MPI status log in startup
  src/main.cpp
  src/main_test.cpp
  src/shamcomm/include/shamcomm/mpiInfo.hpp
  src/shamcomm/include/shamcomm/worldInfo.hpp
  src/shamcomm/src/mpiInfo.cpp
  src/shamcomm/src/worldInfo.cpp
  src/shamsys/include/shamsys/NodeInstance.hpp
  src/shamsys/src/NodeInstance.cpp
  src/shamsys/src/shamrock_smi.cpp
Labels: In-review

#985 [Ramses][solvergraph PR 6] Use distributed refs instead of copy
  src/shammodels/ramses/src/modules/ConsToPrimDust.cpp
  src/shammodels/ramses/src/modules/ConsToPrimGas.cpp
Labels: In-review

#988 sod_tube_zeus.py: Fix undefined name vx
  exemples/ci_tests/sod_tube_zeus.py
  src/shambindings/src/run_ipython.py
Labels: In-review

#989 [Doc] replace shamrock homebrew tap refs by homebrew-core
  README.md
  doc/mkdocs/docs/usermanual/quickstart.md
  doc/mkdocs/docs/usermanual/quickstart/install_brew.md
Labels: In-review

#993 [Ramses][solvergraph PR 7] Use NodeBuildTrees instead of legacy AMRTree
  src/shammodels/ramses/CMakeLists.txt
  src/shammodels/ramses/include/shammodels/ramses/modules/AMRTree.hpp
  src/shammodels/ramses/include/shammodels/ramses/modules/SolverStorage.hpp
  src/shammodels/ramses/src/Solver.cpp
  src/shammodels/ramses/src/modules/AMRGraphGen.cpp
  src/shammodels/ramses/src/modules/AMRTree.cpp
  src/shammodels/ramses/src/modules/StencilGenerator.cpp
Labels: Draft

#996 [Ramses][solvergraph PR 9] Merge beginning of the step as a single OperationSequence
  src/shammodels/ramses/CMakeLists.txt
  src/shammodels/ramses/include/shammodels/ramses/modules/AMRGraphGen.hpp
  src/shammodels/ramses/include/shammodels/ramses/modules/SolverStorage.hpp
  src/shammodels/ramses/src/Solver.cpp
  src/shammodels/ramses/src/modules/AMRGraphGen.cpp
  src/shammodels/ramses/src/modules/BlockNeighToCellNeigh.cpp
  src/shammodels/ramses/src/modules/ComputeFlux.cpp
  src/shammodels/ramses/src/modules/ComputeGradient.cpp
  src/shammodels/ramses/src/modules/ComputeTimeDerivative.cpp
  src/shammodels/ramses/src/modules/FaceInterpolate.cpp
  src/shammodels/ramses/src/modules/FindBlockNeigh.cpp
  src/shammodels/ramses/src/modules/NodeBuildTrees.cpp
  src/shamrock/include/shamrock/solvergraph/NodeFreeAlloc.hpp
  src/shamrock/src/solvergraph/OperationSequence.cpp
Labels: In-review

#997 [Ramses][solvergraph PR 10] Move ComputeAABB node in main solver sequence
  src/shammodels/ramses/CMakeLists.txt
  src/shammodels/ramses/include/shammodels/ramses/modules/ComputeCellInfos.hpp
  src/shammodels/ramses/include/shammodels/ramses/modules/SolverStorage.hpp
  src/shammodels/ramses/src/Solver.cpp
  src/shammodels/ramses/src/modules/ComputeCFL.cpp
  src/shammodels/ramses/src/modules/ComputeCellInfos.cpp
  src/shammodels/ramses/src/modules/ComputeGradient.cpp
  src/shammodels/ramses/src/modules/ComputeTimeDerivative.cpp
  src/shammodels/ramses/src/modules/FaceInterpolate.cpp
Labels: In-review

#1001 [Ramses] migrate link fields & AMRGraph to USM
  src/shambackends/include/shambackends/DeviceBuffer.hpp
  src/shammodels/common/include/shammodels/common/amr/NeighGraph.hpp
  src/shammodels/common/include/shammodels/common/amr/NeighGraphLinkField.hpp
  src/shammodels/ramses/include/shammodels/ramses/modules/details/compute_neigh_graph.hpp
  src/shammodels/ramses/src/modules/BlockNeighToCellNeigh.cpp
  src/shammodels/ramses/src/modules/ComputeTimeDerivative.cpp
  src/shammodels/ramses/src/modules/FindBlockNeigh.cpp
  src/shammodels/ramses/src/modules/SlopeLimitedGradient.cpp
  src/tests/shambackends/DeviceBufferTests.cpp
Labels: In-review

#1003 [Base] use numerical limits to set shortcut one
  src/shambase/include/shambase/aliases_int.hpp
  src/shambase/include/shambase/numeric_limits.hpp
  src/shambase/src/profiling/chrome.cpp
  src/shamcomm/src/logs.cpp
  src/shampylib/src/pyShamsys.cpp
Labels: In-review

#1011 [Ramses][solvergraph PR 12] Migrate face interpolate to use NeighGrapkLinkFieldEdge
  src/shambackends/include/shambackends/kernel_call.hpp
  src/shammodels/common/include/shammodels/common/amr/NeighGraphLinkField.hpp
  src/shammodels/ramses/include/shammodels/ramses/modules/SolverStorage.hpp
  src/shammodels/ramses/include/shammodels/ramses/solvegraph/NeighGrapkLinkFieldEdge.hpp
  src/shammodels/ramses/include/shammodels/ramses/solvegraph/OrientedAMRGraphEdge.hpp
  src/shammodels/ramses/src/Solver.cpp
  src/shammodels/ramses/src/modules/ComputeFlux.cpp
  src/shammodels/ramses/src/modules/FaceInterpolate.cpp
Labels: Draft

#1017 [Backends] improve the log message on failled alloc
  src/shambackends/src/details/internal_alloc.cpp
Labels: In-review

#1023 [Env][dgxcbp] add a binding script
  env/machine/dgx-cbp/acpp-cuda/binding_script.sh
  env/machine/dgx-cbp/acpp-cuda/setup-env.py
  env/machine/dgx-cbp/acpp-sscp/binding_script.sh
  env/machine/dgx-cbp/acpp-sscp/setup-env.py
  env/machine/dgx-cbp/intel-llvm/binding_script.sh
  env/machine/dgx-cbp/intel-llvm/setup-env.py
Labels: In-review
