Repository Shamrock-code/Shamrock, pull requests merged in 2025-09, with the labels that each got.

#1243 [Algs] make impl control API more consistent
  doc/sphinx/examples/benchmarks/run_dtt_performance.py
  doc/sphinx/examples/benchmarks/run_exclusive_scan_in_place.py
  doc/sphinx/examples/benchmarks/run_is_all_true_performance.py
  doc/sphinx/examples/benchmarks/run_reduction_performance.py
  src/shamalgs/include/shamalgs/impl_utils.hpp
  src/shamalgs/include/shamalgs/primitives/is_all_true.hpp
  src/shamalgs/include/shamalgs/primitives/reduction.hpp
  src/shamalgs/include/shamalgs/primitives/scan_exclusive_sum_in_place.hpp
  src/shamalgs/src/primitives/is_all_true.cpp
  src/shamalgs/src/primitives/reduction.cpp
  src/shamalgs/src/primitives/scan_exclusive_sum_in_place.cpp
  src/shampylib/src/pyShamalgs.cpp
  src/shampylib/src/pyShamtree.cpp
  src/shamtree/include/shamtree/CLBVHDualTreeTraversal.hpp
  src/shamtree/src/CLBVHDualTreeTraversal.cpp
  src/tests/shamalgs/primitives/is_all_trueTests.cpp
  src/tests/shamalgs/primitives/reductionTests.cpp
  src/tests/shamalgs/primitives/scan_exclusive_sum_in_placeTests.cpp
  src/tests/shamtree/DTTTesting_tests.cpp
Labels: In-review

#1244 [Bindings] fix sys.stdout hook when using ipython
  src/shambase/src/print.cpp
  src/shambindings/CMakeLists.txt
  src/shambindings/include/shambindings/pybindings.hpp
  src/shambindings/src/pybindings.cpp
Labels: Polishing

#1247 [Solvergraph] rename ITDataEdge to IDataEdge
  src/shammodels/ramses/include/shammodels/ramses/modules/FindGhostLayerCandidates.hpp
  src/shammodels/ramses/include/shammodels/ramses/modules/SolverStorage.hpp
  src/shammodels/ramses/src/Solver.cpp
  src/shamrock/include/shamrock/solvergraph/IDataEdge.hpp
Labels: In-review

#1242 [SPH] wrap smoothing length iteration in new module
  src/shammodels/sph/CMakeLists.txt
  src/shammodels/sph/include/shammodels/sph/modules/LoopSmoothingLengthIter.hpp
  src/shammodels/sph/src/Solver.cpp
  src/shammodels/sph/src/modules/LoopSmoothingLengthIter.cpp
  src/shamrock/include/shamrock/solvergraph/IFieldRefs.hpp
Labels: In-review

#1108 [SPH] Disc analysis module
  src/shamalgs/include/shamalgs/details/numeric/numeric.hpp
  src/shamalgs/include/shamalgs/primitives/linspace.hpp
  src/shammodels/sph/CMakeLists.txt
  src/shammodels/sph/include/shammodels/sph/modules/AnalysisDisc.hpp
  src/shammodels/sph/src/modules/AnalysisDisc.cpp
  src/shammodels/sph/src/pySPHModel.cpp
Labels: Polishing

#1261 [SPH] add double hump kernels & shifted splines
  doc/sphinx/examples/sph/run_show_all_sph_kernels.py
  src/shammath/include/shammath/sphkernels.hpp
  src/shampylib/src/math/pySPHKernels.cpp
  src/tests/shammath/sphkernelsTests.cpp
Labels: Polishing

#1264 [SPH] add a module to compute stats on neigh counts
  src/shammodels/sph/CMakeLists.txt
  src/shammodels/sph/include/shammodels/sph/SolverConfig.hpp
  src/shammodels/sph/include/shammodels/sph/modules/ComputeNeighStats.hpp
  src/shammodels/sph/include/shammodels/sph/solvergraph/NeighCache.hpp
  src/shammodels/sph/src/Solver.cpp
  src/shammodels/sph/src/modules/ComputeNeighStats.cpp
  src/shammodels/sph/src/pySPHModel.cpp
Labels: Draft

#1265 [SPH] migrate compute omega from shamrock pre-history to modern age
  src/shammodels/sph/src/modules/ComputeOmega.cpp
Labels: In-review

#1271 [SPH] use json serializer to display solver config
  src/shammodels/sph/include/shammodels/sph/SolverConfig.hpp
Labels: Polishing

#1273 [Algs] migrate gen_buffer_index to primitives
  src/shamalgs/CMakeLists.txt
  src/shamalgs/include/shamalgs/details/algorithm/algorithm.hpp
  src/shamalgs/include/shamalgs/primitives/gen_buffer_index.hpp
  src/shamalgs/src/details/algorithm/algorithm.cpp
  src/shamalgs/src/primitives/gen_buffer_index.cpp
  src/shamtree/src/MortonCodeSortedSet.cpp
  src/tests/shamalgs/algorithm/sortTests.hpp
  src/tests/shamalgs/primitives/gen_buffer_indexTests.cpp
Labels: Polishing

#1279 [Solvergraph] add CopyPatchDataField node
  src/shamrock/include/shamrock/solvergraph/CopyPatchDataField.hpp
  src/shamrock/src/solvergraph/CopyPatchDataField.cpp
  src/tests/shamrock/solvergraph/CopyPatchDataField_tests.cpp
Labels: In-review

#1282 [CI] do not remove image after run to allow retries
  .github/workflows/shamrock-acpp-phys-test.yml
Labels: Polishing

#1284 [SPH] add cumulated step count & time to sph solver logs
  doc/sphinx/examples/sph/run_circular_disc_central_pot.py
  doc/sphinx/examples/sph/run_circular_disc_sink.py
  src/shammodels/sph/include/shammodels/sph/Model.hpp
  src/shammodels/sph/include/shammodels/sph/SolverLog.hpp
  src/shammodels/sph/src/pySPHModel.cpp
Labels: In-review

#1285 [SPH] add config entry for particle sorting
  src/shammodels/sph/include/shammodels/sph/SolverConfig.hpp
  src/shammodels/sph/src/Solver.cpp
  src/shammodels/sph/src/pySPHModel.cpp
Labels: In-review

#1286 [Base] move macro for unique name generation in standalone header
  src/shambase/include/shambase/stacktrace.hpp
  src/shambase/include/shambase/unique_name_macro.hpp
  src/tests/shambase/unique_name_macro_test.cpp
Labels: ready-to-merge

#1293 [Base] add PRE_MAIN_FUNCTION_CALL to run stuff before main
  src/shambase/include/shambase/pre_main_call.hpp
  src/tests/shambase/pre_main_call_tests.cpp
Labels: in-review

#1297 [Solvergraph] add a function to debug nodes connections
  src/shamrock/include/shamrock/solvergraph/INode.hpp
Labels: ready-to-merge

#1299 [AMR] fix some warnings in DragIntegrator
  src/shammodels/ramses/src/modules/DragIntegrator.cpp
Labels: ready-to-merge

#1301 [Sys] improve POSIX signal handling & add report on sigsev
  src/main_test.cpp
  src/shamsys/src/SignalCatch.cpp
Labels: ready-to-merge
