Repository Shamrock-code/Shamrock, pull requests merged in 2025-07, with the labels that each got.

#1086 [SPH] make neigh cache a solvergraph edge
  src/shammodels/sph/include/shammodels/sph/Solver.hpp
  src/shammodels/sph/include/shammodels/sph/SolverConfig.hpp
  src/shammodels/sph/include/shammodels/sph/modules/SolverStorage.hpp
  src/shammodels/sph/include/shammodels/sph/solvergraph/NeighCache.hpp
  src/shammodels/sph/src/Model.cpp
  src/shammodels/sph/src/Solver.cpp
  src/shammodels/sph/src/modules/ComputeOmega.cpp
  src/shammodels/sph/src/modules/DiffOperator.cpp
  src/shammodels/sph/src/modules/DiffOperatorDtDivv.cpp
  src/shammodels/sph/src/modules/NeighbourCache.cpp
  src/shammodels/sph/src/modules/UpdateDerivs.cpp
  src/shammodels/sph/src/pySPHModel.cpp
Labels: In-review

#1090 [Algs] replace a allgather by work duplication
  src/shamalgs/include/shamalgs/collective/exchanges.hpp
  src/tests/shamalgs/collective/exchangeTests.cpp
Labels: In-review

#1095 [Sys] add vector_allgather benchmark to microbenchmarks
  src/shamsys/src/MicroBenchmark.cpp
Labels: In-review

#1094 [Patch] add a USM variant of PatchDataField get_ids_where
  src/shamrock/include/shamrock/patch/PatchDataField.hpp
  src/shamrock/src/patch/PatchDataField.cpp
  src/tests/shamrock/patch/PatchDataFieldTests.cpp
Labels: In-review

#1097 [Doc] add recommended configs
  doc/mkdocs/docs/usermanual/quickstart.md
  doc/mkdocs/docs/usermanual/quickstart/recommended_config/conda.md
  doc/mkdocs/docs/usermanual/quickstart/recommended_config/linux_debian.md
  doc/mkdocs/docs/usermanual/quickstart/recommended_config/macos.md
  doc/mkdocs/mkdocs.yml
Labels: documentation, In-review

#1103 [All] more get_check_ref instead of direct dereferencing
  src/shammodels/sph/src/Solver.cpp
  src/shamsys/src/MicroBenchmark.cpp
  src/shamsys/src/NodeInstance.cpp
Labels: In-review

#1100 [SPH] migrate ghosts cache indexes to USM
  src/shammodels/sph/include/shammodels/sph/BasicSPHGhosts.hpp
  src/shammodels/sph/src/BasicSPHGhosts.cpp
  src/shammodels/sph/src/Solver.cpp
Labels: In-review

#1045 [Tests][Algs] add some checks in sparse comm tests
  src/tests/shamalgs/collective/sparseXchgTests.cpp
Labels: In-review

#1104 [SPH] add solvergraph field refs for merged pos & h
  src/shammodels/sph/include/shammodels/sph/modules/SolverStorage.hpp
  src/shammodels/sph/src/Solver.cpp
Labels: Draft

#1116 [SPH] add AnalysisSPH module with method to compute barycenter
  src/shammodels/sph/CMakeLists.txt
  src/shammodels/sph/include/shammodels/sph/modules/AnalysisBarycenter.hpp
  src/shammodels/sph/src/modules/AnalysisBarycenter.cpp
  src/shammodels/sph/src/pySPHModel.cpp
Labels: Polishing

#1050 [Env] add a shorthand to reset the current env files + add run_precommit util
  doc/mkdocs/docs/usermanual/envs.md
  env/helpers/precommit_util.sh
  env/machine/argonne/aurora/env_oneapi.sh
  env/machine/ci/intel-llvm/cuda/env_built_intel-llvm.sh
  env/machine/ci/intel-llvm/rocm/env_built_intel-llvm.sh
  env/machine/docker/intel_oneapi/env_built_intel-llvm.sh
  env/machine/lumi/g/acpp-rocm-llvm/env_built_acpp.sh
  env/machine/nixos/acpp/setup-env.py
  env/new-env
  env/utils/setuparg.py
Labels: Polishing

#1129 [Tree] implement USM variant of tree fields
  src/shamtree/include/shamtree/KarrasRadixTreeField.hpp
  src/tests/shamtree/KarrasRadixTreeFieldTests.cpp
Labels: In-review

#1131 [CI] automatically check authorship change in sources using pre-commit
  .pre-commit-config.yaml
  buildbot/precommit_report.py
  buildbot/update_authors.py
Labels: In-review

#1134 [Tree] tweaks to CLBVH for SPH migration
  src/shamtree/include/shamtree/CLBVHObjectIterator.hpp
  src/shamtree/include/shamtree/CompressedLeafBVH.hpp
  src/shamtree/include/shamtree/TreeTraversal.hpp
  src/shamtree/src/CompressedLeafBVH.cpp
  src/shamtree/src/KarrasRadixTreeAABB.cpp
Labels: In-review

#1136 [Ramses] add node to compute block levels
  src/shambackends/include/shambackends/math.hpp
  src/shammodels/ramses/CMakeLists.txt
  src/shammodels/ramses/include/shammodels/ramses/modules/ComputeAMRLevel.hpp
  src/shammodels/ramses/src/modules/ComputeAMRLevel.cpp
  src/shamrock/include/shamrock/solvergraph/ScalarsEdge.hpp
  src/tests/shambackends/mathTests.cpp
  src/tests/shammodels/ramses/modules/ComputeAMRLevelTests.cpp
Labels: In-review

#1121 [Ramses][Conjugate gradient] dot product of the residual vector
  src/shammodels/ramses/CMakeLists.txt
  src/shammodels/ramses/include/shammodels/ramses/SolverConfig.hpp
  src/shammodels/ramses/include/shammodels/ramses/modules/ResidualDot.hpp
  src/shammodels/ramses/src/modules/ResidualDot.cpp
  src/shammodels/ramses/src/pyRamsesModel.cpp
Labels: In-review

#1092 [Examples] advection through patches test
  doc/sphinx/cmake_sphinx.sh
  doc/sphinx/examples/sph/run_advect_sphere_domain_decomp.py
  doc/sphinx/source/conf.py
  src/shammodels/sph/include/shammodels/sph/Model.hpp
  src/shammodels/sph/include/shammodels/sph/Solver.hpp
  src/shammodels/sph/src/Solver.cpp
  src/shammodels/sph/src/pySPHModel.cpp
  src/shampylib/src/pyShamrockCtx.cpp
  src/shamrock/include/shamrock/patch/PatchCoordTransform.hpp
  src/shamrock/include/shamrock/scheduler/ShamrockCtx.hpp
  src/shamrock/src/scheduler/PatchScheduler.cpp
Labels: In-review

#1139 [Doc] animate SPH shearing box example
  doc/sphinx/examples/sph/run_advect_sphere_domain_decomp.py
  doc/sphinx/examples/sph/run_sph_shear_test.py
Labels: In-review

#1140 [Doc] 3d gaussian generator & unit vector generator
  doc/sphinx/examples/math/run_mock_3d_gaussian.py
  doc/sphinx/examples/math/run_mock_unit_vector.py
  src/shamalgs/include/shamalgs/details/random/random.hpp
  src/shampylib/src/pyShamalgs.cpp
Labels: In-review

#1144 [CI] blacklist gemini from update author script
  buildbot/update_authors.py
Labels: Polishing

#1142 [Backends] add .append() function to buffers
  src/shambackends/include/shambackends/DeviceBuffer.hpp
  src/tests/shambackends/DeviceBufferTests.cpp
Labels: Polishing

#1145 [Base] fix typo in shambase::parallel_for
  cmake/ShamConfigureSYCL.cmake
  doc/mkdocs/docs/syclguide/sycl_tricks.md
  src/shamalgs/include/shamalgs/details/memory/memory.hpp
  src/shamalgs/include/shamalgs/details/numeric/scanDecoupledLookback.hpp
  src/shamalgs/src/details/algorithm/bitonicSort_updated.cpp
  src/shambackends/include/shambackends/DeviceBuffer.hpp
  src/shambackends/include/shambackends/USMBufferInterop.hpp
  src/shambackends/include/shambackends/sycl_utils.hpp
  src/shammodels/common/include/shammodels/common/amr/AMRBlock.hpp
  src/shammodels/common/include/shammodels/common/amr/NeighGraphLinkField.hpp
  src/shammodels/ramses/include/shammodels/ramses/modules/ComputeFluxUtilities.hpp
  src/shammodels/ramses/include/shammodels/ramses/modules/details/compute_neigh_graph.hpp
  src/shammodels/ramses/src/Model.cpp
  src/shammodels/ramses/src/Solver.cpp
  src/shammodels/ramses/src/modules/CGInit.cpp
  src/shammodels/ramses/src/modules/ComputeCFL.cpp
  src/shammodels/ramses/src/modules/ComputeTimeDerivative.cpp
  src/shammodels/ramses/src/modules/DragIntegrator.cpp
  src/shammodels/ramses/src/modules/GhostZones.cpp
  src/shammodels/ramses/src/modules/NodeBuildTrees.cpp
  src/shammodels/ramses/src/modules/SlopeLimitedGradient.cpp
  src/shammodels/ramses/src/modules/StencilGenerator.cpp
  src/shammodels/ramses/src/modules/TimeIntegrator.cpp
  src/shammodels/sph/src/SPHUtilities.cpp
  src/shammodels/sph/src/Solver.cpp
  src/shammodels/sph/src/modules/BuildTrees.cpp
  src/shammodels/sph/src/modules/DiffOperator.cpp
  src/shammodels/sph/src/modules/DiffOperatorDtDivv.cpp
  src/shammodels/sph/src/modules/ExternalForces.cpp
  src/shammodels/sph/src/modules/NeighbourCache.cpp
  src/shammodels/sph/src/modules/SinkParticlesUpdate.cpp
  src/shammodels/sph/src/modules/UpdateDerivs.cpp
  src/shammodels/sph/src/modules/render/CartesianRender.cpp
  src/shammodels/sph/src/modules/setup/ModifierApplyDiscWarp.cpp
  src/shammodels/sph/src/modules/setup/ModifierOffset.cpp
  src/shammodels/zeus/src/Model.cpp
  src/shammodels/zeus/src/Solver.cpp
  src/shammodels/zeus/src/modules/AMRTree.cpp
  src/shammodels/zeus/src/modules/ComputePressure.cpp
  src/shammodels/zeus/src/modules/DiffOperator.cpp
  src/shammodels/zeus/src/modules/FaceFlagger.cpp
  src/shammodels/zeus/src/modules/GhostZones.cpp
  src/shammodels/zeus/src/modules/SourceStep.cpp
  src/shammodels/zeus/src/modules/ValueLoader.cpp
  src/shammodels/zeus/src/modules/WriteBack.cpp
  src/shamrock/include/shamrock/patch/PatchDataField.hpp
  src/shamrock/include/shamrock/scheduler/loadbalance/LoadBalanceStrategy.hpp
  src/tests/shamalgs/container/ResizableUSMBufferTests.cpp
  src/tests/shambase/syclUtilsTests.cpp
  src/tests/shammath/sphkernelsTests.cpp
  src/tests/shamrock/scheduler/LoadBalanceTests.cpp
  src/tests/shamsys/syclLoopsTests.cpp
Labels: Polishing

#1146 [Doc][Examples] add uniform SPH box
  doc/sphinx/examples/sph/run_uniform_box.py
Labels: In-review

#1147 [Doc][Examples] add KH instab in SPH
  doc/sphinx/examples/sph/run_kelvin_helmholtz.py
Labels: In-review

#1130 [SPH][Tree] swap SPH tree to usm variant
  src/shammodels/sph/include/shammodels/sph/SolverConfig.hpp
  src/shammodels/sph/include/shammodels/sph/modules/SolverStorage.hpp
  src/shammodels/sph/src/Solver.cpp
  src/shammodels/sph/src/modules/BuildTrees.cpp
  src/shammodels/sph/src/modules/NeighbourCache.cpp
Labels: Polishing

#1149 [Examples] move ci tests to sphinx doc and symlink them to exemples
  doc/sphinx/examples/tests_ci/GALLERY_HEADER.rst
  doc/sphinx/examples/tests_ci/comp_phantom_sedov_1patch.py
  doc/sphinx/examples/tests_ci/comp_phantom_sedov_8patch.py
  doc/sphinx/examples/tests_ci/dustybox_godunov.py
  doc/sphinx/examples/tests_ci/dustywave_godunov.py
  doc/sphinx/examples/tests_ci/reload_old_dump.py
  doc/sphinx/examples/tests_ci/sod_tube_godunov.py
  doc/sphinx/examples/tests_ci/sod_tube_godunov_amr.py
  doc/sphinx/examples/tests_ci/sod_tube_sph.py
  doc/sphinx/examples/tests_ci/sod_tube_zeus.py
  exemples/ci_tests
Labels: In-review

#1151 [Algs] fix the size error that made the bitonic sort sad
  src/shamalgs/src/details/numeric/numeric.cpp
Labels: In-review

#1150 [CI] add SPH regression testing on KH & disc
  .github/dockerfiles/phys_test_image_acpp_omp/Dockerfile
  .github/workflows/shamrock-acpp-phys-test.yml
  doc/sphinx/examples/tests_ci/regression_sph_disc.py
  doc/sphinx/examples/tests_ci/regression_sph_kh.py
Labels: In-review

#1157 [SPH] Enable Wendland kernels C2, C4, C6
  src/shammodels/sph/src/Model.cpp
  src/shammodels/sph/src/SPHUtilities.cpp
  src/shammodels/sph/src/Solver.cpp
  src/shammodels/sph/src/SolverConfig.cpp
  src/shammodels/sph/src/modules/AnalysisBarycenter.cpp
  src/shammodels/sph/src/modules/AnalysisSodTube.cpp
  src/shammodels/sph/src/modules/BuildTrees.cpp
  src/shammodels/sph/src/modules/ComputeEos.cpp
  src/shammodels/sph/src/modules/ComputeLoadBalanceValue.cpp
  src/shammodels/sph/src/modules/ComputeOmega.cpp
  src/shammodels/sph/src/modules/ConservativeCheck.cpp
  src/shammodels/sph/src/modules/DiffOperator.cpp
  src/shammodels/sph/src/modules/DiffOperatorDtDivv.cpp
  src/shammodels/sph/src/modules/ExternalForces.cpp
  src/shammodels/sph/src/modules/NeighbourCache.cpp
  src/shammodels/sph/src/modules/ParticleReordering.cpp
  src/shammodels/sph/src/modules/SPHSetup.cpp
  src/shammodels/sph/src/modules/SinkParticlesUpdate.cpp
  src/shammodels/sph/src/modules/UpdateDerivs.cpp
  src/shammodels/sph/src/modules/UpdateViscosity.cpp
  src/shammodels/sph/src/modules/io/VTKDump.cpp
  src/shammodels/sph/src/modules/render/CartesianRender.cpp
  src/shammodels/sph/src/modules/render/RenderFieldGetter.cpp
  src/shammodels/sph/src/modules/setup/GeneratorMCDisc.cpp
  src/shammodels/sph/src/modules/setup/ModifierApplyDiscWarp.cpp
  src/shammodels/sph/src/modules/setup/ModifierFilter.cpp
  src/shammodels/sph/src/modules/setup/ModifierOffset.cpp
  src/shammodels/sph/src/pySPHModel.cpp
  src/shampylib/src/math/pySPHKernels.cpp
Labels: In-review
