Repository Shamrock-code/Shamrock, pull requests merged in 2025-06, with the labels that each got.

#1013 [Ramses] rho mean module
  src/shammodels/ramses/CMakeLists.txt
  src/shammodels/ramses/include/shammodels/ramses/SolverConfig.hpp
  src/shammodels/ramses/include/shammodels/ramses/modules/ComputeRhoMean.hpp
  src/shammodels/ramses/src/Solver.cpp
  src/shammodels/ramses/src/modules/ComputeRhoMean.cpp
  src/shamrock/src/scheduler/PatchScheduler.cpp
Labels: Polishing

#1020 [CI] add the long version of phantom comp to physical tests
  .github/workflows/shamrock-acpp-phys-test.yml
  exemples/ci_tests/comp_phantom_sedov.py
  src/shammodels/sph/include/shammodels/sph/Model.hpp
  src/shammodels/sph/src/pySPHModel.cpp
Labels: Polishing

#1024 [Ramses][solvergraph PR 14] Migrate ComputeRhoMean
  src/shammodels/ramses/CMakeLists.txt
  src/shammodels/ramses/include/shammodels/ramses/modules/ComputeMass.hpp
  src/shammodels/ramses/include/shammodels/ramses/modules/ComputeRhoMean.hpp
  src/shammodels/ramses/include/shammodels/ramses/modules/ComputeSumOverV.hpp
  src/shammodels/ramses/include/shammodels/ramses/modules/SolverStorage.hpp
  src/shammodels/ramses/src/Solver.cpp
  src/shammodels/ramses/src/modules/ComputeMass.cpp
  src/shammodels/ramses/src/modules/ComputeRhoMean.cpp
  src/shammodels/ramses/src/modules/ComputeSumOverV.cpp
  src/shammodels/ramses/src/modules/GhostZones.cpp
  src/shamrock/include/shamrock/solvergraph/ScalarEdge.hpp
Labels: In-review

#1008 [SPH] Improve Shamrock handling of phantom dumps (+ fix for MCFost)
  exemples/ci_tests/comp_phantom_sedov.py
  exemples/test_ph_dump_writer.py
  src/shamcomm/src/logs.cpp
  src/shammodels/sph/CMakeLists.txt
  src/shammodels/sph/include/shammodels/sph/io/Phantom2Shamrock.hpp
  src/shammodels/sph/include/shammodels/sph/io/PhantomDump.hpp
  src/shammodels/sph/include/shammodels/sph/io/PhantomDumpEOSUtils.hpp
  src/shammodels/sph/src/Model.cpp
  src/shammodels/sph/src/io/Phantom2Shamrock.cpp
  src/shammodels/sph/src/io/PhantomDump.cpp
  src/shammodels/sph/src/io/PhantomDumpEOSUtils.cpp
  src/shammodels/sph/src/pyPhantomDump.cpp
  src/tests/phantom_read_test.cpp
Labels: In-review

#1029 [SPH][Setup] add setup particle filter
  src/shammodels/sph/CMakeLists.txt
  src/shammodels/sph/include/shammodels/sph/modules/SPHSetup.hpp
  src/shammodels/sph/include/shammodels/sph/modules/setup/ModifierFilter.hpp
  src/shammodels/sph/src/modules/SPHSetup.cpp
  src/shammodels/sph/src/modules/setup/ModifierFilter.cpp
  src/shammodels/sph/src/pySPHModel.cpp
  src/shamrock/include/shamrock/patch/PatchData.hpp
  src/shamrock/src/patch/PatchData.cpp
Labels: In-review

#916 [Ramses] Drag exponential solver
  exemples/godunov_dusty_collision_test.py
  exemples/godunov_dusty_wave_test.py
  src/shammodels/ramses/include/shammodels/ramses/modules/DragIntegrator.hpp
  src/shammodels/ramses/src/Solver.cpp
  src/shammodels/ramses/src/modules/DragIntegrator.cpp
Labels: Polishing

#1027 [Backends] wrap allocs in try catch
  src/shambackends/src/details/internal_alloc.cpp
Labels: Polishing

#1042 [Tree] implement the USM variant of RadixTree (LeafCompressedBVH)
  src/shamtree/CMakeLists.txt
  src/shamtree/include/shamtree/CLBVHObjectIterator.hpp
  src/shamtree/include/shamtree/CompressedLeafBVH.hpp
  src/shamtree/include/shamtree/KarrasRadixTree.hpp
  src/shamtree/include/shamtree/KarrasRadixTreeAABB.hpp
  src/shamtree/include/shamtree/KarrasTreeTraverser.hpp
  src/shamtree/include/shamtree/MortonCodeSortedSet.hpp
  src/shamtree/include/shamtree/MortonReducedSet.hpp
  src/shamtree/src/CompressedLeafBVH.cpp
  src/shamtree/src/KarrasRadixTreeAABB.cpp
  src/shamtree/src/MortonCodeSet.cpp
  src/shamtree/src/MortonCodeSortedSet.cpp
  src/shamtree/src/MortonReducedSet.cpp
  src/tests/shamtree/CLBVHObjectIteratorTests.cpp
Labels: In-review

#1046 [Backends] remove some ambiguous uses of get_bytesize
  src/shamalgs/include/shamalgs/collective/sparseXchg.hpp
  src/shambackends/include/shambackends/DeviceBuffer.hpp
  src/shambackends/include/shambackends/comm/CommunicationBuffer.hpp
  src/shambackends/include/shambackends/comm/details/CommunicationBufferImpl.hpp
  src/shamrock/src/scheduler/PatchScheduler.cpp
  src/shamrock/src/scheduler/SchedulerPatchData.cpp
Labels: In-review

#1048 [Env] add the kraken-gpu UGA cluster
  env/machine/uga/kraken-gpu/env_oneapi.sh
  env/machine/uga/kraken-gpu/setup-env.py
Labels: In-review

#1049 [SPH] fix sink de-sync when some processes have no patches
  src/shammodels/sph/src/modules/SinkParticlesUpdate.cpp
Labels: In-review

#1016 [Ramses][gravity] Set gravity potential and add it in ghost zones
  src/shammodels/ramses/include/shammodels/ramses/SolverConfig.hpp
  src/shammodels/ramses/src/modules/GhostZones.cpp
Labels: Draft

#1051 [Comm] introduce a new MPI wrapper to time MPI calls
  src/shambase/include/shambase/profiling/profiling.hpp
  src/shambase/src/profiling/profiling.cpp
  src/shamcomm/CMakeLists.txt
  src/shamcomm/include/shamcomm/wrapper.hpp
  src/shamcomm/src/collectives.cpp
  src/shamcomm/src/worldInfo.cpp
  src/shamcomm/src/wrapper.cpp
Labels: In-review

#1053 [Ramses] Add passive scalars to config + bindings
  src/shammodels/ramses/include/shammodels/ramses/Solver.hpp
  src/shammodels/ramses/include/shammodels/ramses/SolverConfig.hpp
  src/shammodels/ramses/src/pyRamsesModel.cpp
Labels: In-review

#1055 [Ramses] Add gas passive scalars in ghost zone
  src/shammodels/ramses/src/modules/GhostZones.cpp
Labels: Draft

#1058 [Doc] update llvm version to 18 in quickstart
  doc/mkdocs/docs/usermanual/quickstart/install_from_source.md
Labels: In-review

#1061 [Backend] more elegant handling of alloc alignment
  src/shambackends/include/shambackends/Device.hpp
  src/shambackends/include/shambackends/DeviceBuffer.hpp
  src/shambackends/src/Device.cpp
  src/shambackends/src/details/internal_alloc.cpp
  src/shamtree/include/shamtree/TreeTraversal.hpp
  src/tests/shambackends/DeviceBufferTests.cpp
  src/tests/shambackends/usmbufferTests.cpp
Labels: In-review

#1062 [Comm] use the new MPI wrapper and report MPI timings in logs
  src/shamalgs/include/shamalgs/collective/exchanges.hpp
  src/shamalgs/include/shamalgs/collective/indexing.hpp
  src/shamalgs/include/shamalgs/collective/io.hpp
  src/shamalgs/include/shamalgs/collective/reduction.hpp
  src/shambackends/src/comm/CommunicationBuffer.cpp
  src/shammodels/common/include/shammodels/common/timestep_report.hpp
  src/shammodels/nbody/include/shammodels/nbody/setup/nbody_setup.hpp
  src/shammodels/ramses/src/Solver.cpp
  src/shammodels/sph/src/Solver.cpp
  src/shammodels/sph/src/modules/ComputeLoadBalanceValue.cpp
  src/shammodels/zeus/src/Solver.cpp
  src/shamrock/include/shamrock/io/LegacyVtkWritter.hpp
  src/shamrock/include/shamrock/legacy/comm/sparse_communicator_impl.hpp
  src/shamrock/include/shamrock/legacy/io/dump.hpp
  src/shamrock/include/shamrock/legacy/patch/base/patchdata.hpp
  src/shamrock/include/shamrock/legacy/patch/base/patchdata_field.hpp
  src/shamrock/include/shamrock/legacy/patch/comm/patchdata_exchanger_impl.hpp
  src/shamrock/include/shamrock/scheduler/DataInserterUtility.hpp
  src/shamrock/src/legacy/patch/utility/global_var.cpp
  src/shamrock/src/scheduler/PatchScheduler.cpp
  src/shamrock/src/scheduler/SchedulerPatchData.cpp
  src/shamrock/src/scheduler/scheduler_patch_list.cpp
  src/shamsys/include/shamsys/legacy/sycl_mpi_interop.hpp
  src/shamsys/src/MicroBenchmark.cpp
  src/shamsys/src/NodeInstance.cpp
  src/shamsys/src/legacy/sycl_mpi_interop.cpp
  src/tests/shamrock/patch/patchTests.cpp
  src/tests/shamsys/BandwithTests.cpp
  src/tests/shamsys/legacy/test_sycl_mpi_interop.cpp
Labels: In-review

#1056 [MHD] add a push_particle that also pushes B and psi.
  src/shammodels/sph/include/shammodels/sph/Model.hpp
  src/shammodels/sph/include/shammodels/sph/SolverConfig.hpp
  src/shammodels/sph/src/Model.cpp
  src/shammodels/sph/src/pySPHModel.cpp
Labels: Polishing

#1065 [Ramses][DragIntegrator] Ajuste work-group-size
  src/shammodels/ramses/src/modules/DragIntegrator.cpp
Labels: In-review

#1054 [Backends] Implement the GPU core timeline tool from A. Richermoz, F. Neyret 2024
  buildbot/gpu_core_timeline_read.py
  src/shambackends/include/shambackends/gpu_core_timeline.hpp
  src/shambackends/include/shambackends/intrisics/get_sm_id.hpp
  src/tests/shambackends/gpu_core_timelineTest.cpp
Labels: In-review

#1076 [Ramses][Config] Check if gamma < 1
  src/shammodels/ramses/include/shammodels/ramses/SolverConfig.hpp
Labels: In-review

#1081 [Ramses] clean some leftovers + add solvergraph python bindings
  src/shammodels/ramses/CMakeLists.txt
  src/shammodels/ramses/include/shammodels/ramses/modules/FaceInterpolate.hpp
  src/shammodels/ramses/src/Solver.cpp
  src/shammodels/ramses/src/modules/FaceInterpolate.cpp
  src/shammodels/ramses/src/pyRamsesModel.cpp
Labels: In-review

#1082 [Ramses][solvergraph PR 16] migrate fluxes to solvergraph
  src/shammodels/common/include/shammodels/common/amr/NeighGraph.hpp
  src/shammodels/common/include/shammodels/common/amr/NeighGraphLinkField.hpp
  src/shammodels/ramses/CMakeLists.txt
  src/shammodels/ramses/include/shammodels/ramses/modules/ComputeFlux.hpp
  src/shammodels/ramses/include/shammodels/ramses/modules/ComputeFluxUtilities.hpp
  src/shammodels/ramses/include/shammodels/ramses/modules/NodeComputeFlux.hpp
  src/shammodels/ramses/include/shammodels/ramses/modules/SolverStorage.hpp
  src/shammodels/ramses/include/shammodels/ramses/solvegraph/NeighGrapkLinkFieldEdge.hpp
  src/shammodels/ramses/include/shammodels/ramses/solvegraph/OrientedAMRGraphEdge.hpp
  src/shammodels/ramses/src/Solver.cpp
  src/shammodels/ramses/src/modules/CGInit.cpp
  src/shammodels/ramses/src/modules/ComputeFlux.cpp
  src/shammodels/ramses/src/modules/ComputeTimeDerivative.cpp
  src/shammodels/ramses/src/modules/InterpolateToFace.cpp
  src/shammodels/ramses/src/modules/NodeComputeFlux.cpp
  src/shammodels/ramses/src/modules/SlopeLimitedGradient.cpp
Labels: In-review

#1084 [Base] extend on_distributeddata_diff to only ids case
  src/shambase/include/shambase/DistributedData.hpp
Labels: In-review

#1085 [Patch] add a PatchData function to remove ids
  src/shamrock/include/shamrock/patch/PatchData.hpp
  src/shamrock/include/shamrock/patch/PatchDataField.hpp
  src/shamrock/src/patch/PatchData.cpp
  src/shamrock/src/patch/PatchDataField.cpp
  src/tests/shamrock/patch/PatchDataFieldTests.cpp
Labels: In-review
